server.port=8080

spring.application.name=auth-service
spring.jackson.property-naming-strategy=SNAKE_CASE

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

app.jwt.access-validity-seconds=300
app.jwt.refresh-validity-seconds=64800